apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - api/deployment.yaml
  - api/service.yaml
  - dashboard/deployment.yaml
  - dashboard/service.yaml
  - tenant-demo/deployment.yaml
  - tenant-demo/service.yaml
  - tenant-acme/deployment.yaml
  - tenant-acme/service.yaml
  - rabbitmq/statefulset.yaml
  - redis/statefulset.yaml
  - worker/deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: consultores
