apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-demo
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: docr-credentials
      containers:
        - name: tenant-demo
          imagePullPolicy: Always
          env:
            - name: SSR_API_ORIGIN
              value: "http://api:8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
