apiVersion: v1
kind: Service
metadata:
  name: tenant-demo
  labels:
    app: tenant-demo
spec:
  selector:
    app: tenant-demo
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
  type: ClusterIP
